### ISSUE TITLE
关于摄像头实时推理延迟大的问题

### ISSUE THREAD

**Issue by Y1ZzLu** [leafqycc/rknn-cpp-Multithreading#23]
使用摄像头实时推理的延迟很大，大佬有没有什么解决办法

**Comment by leafqycc** [comment]
因为是异步的，所以线程池越大延迟越高
你可以把线程池的线程数n改成2看看，如果还是接受不了的话就不用线程池优化了）

**Comment by leafqycc** [comment]
如果只有单输入流的情况
也可以考虑把core_mask设置成三个核心并用
这样主进程读取摄像头，再开一个推理线程做异步推理，主进程阻塞交替运行(读取摄像头→异步推理→读取摄像头→获取推理结果→异步推理→读取摄像头→获取推理结果→······)
