### ISSUE TITLE
多阶段问题

### ISSUE THREAD

**Issue by morgan726** [leafqycc/rknn-cpp-Multithreading#27]
你好，如何初始化两个模型 在线程池种完成推理，比如先检测 再姿态或ocr

**Comment by leafqycc** [comment]
> 你好，如何初始化两个模型 在线程池种完成推理，比如先检测 再姿态或ocr

        如果不太在意延迟的话，可以参考yolov5s的类再写一个姿态或ocr模型类，然后初始化两个类的线程池，之后串行检测，目标检测的输出作为姿态或ocr的输入这样子
        或者参考yolov5s的类再写一个姿态或ocr模型类，然后再套一个函数（此函数输入为图片，先进行检测再姿态或ocr，最后输出检测图片）进行封装，稍微修改一下线程池，对该函数进行并发操作；亦或者参照yolov5s的类成员函数，对两个模型类进行封装成类，这样不需要修改线程池，直接用该类对线程池进行初始化就好了
