### ISSUE TITLE
RK3588 无法复现最高FPS130+，实际不到83FPS

### ISSUE THREAD

**Issue by 1qingfeng-1** [leafqycc/rknn-cpp-Multithreading#32]
修改的部分请看：https://github.com/1qingfeng-1/rknn-cpp-Multithreading.git

./rknn_yolov5_demo model/RK3588/yolov5s-640-640.rknn output.mp4

output.mp4 是640*640 60帧的视频

各个步骤耗时 测试结果：
pre_process: 491 us
infer: 19065 us
post_process: 403 us
get show: 13960 us
pre_process: 183 us
infer: 19784 us
post_process: 366 us
get show: 11874 us
pre_process: 298 us
infer: 18670 us
post_process: 415 us
get show: 11531 us
pre_process: 475 us
infer: 19163 us
post_process: 369 us
get show: 12630 us
pre_process: 222 us
infer: 19813 us
post_process: 377 us
get show: 13391 us

可以看到 前处理 不到1ms，推理不到20ms，后处理不到1ms， get show 是13ms(平均)
采用多线程加速，实际帧率是看get show，也就是平均13ms一帧， fps 76帧

**Comment by leafqycc** [comment]
> 修改的部分请看：https://github.com/1qingfeng-1/rknn-cpp-Multithreading.git
> 
> ./rknn_yolov5_demo model/RK3588/yolov5s-640-640.rknn output.mp4
> 
> output.mp4 是640*640 60帧的视频
> 
> 各个步骤耗时 测试结果： pre_process: 491 us infer: 19065 us post_process: 403 us get show: 13960 us pre_process: 183 us infer: 19784 us post_process: 366 us get show: 11874 us pre_process: 298 us infer: 18670 us post_process: 415 us get show: 11531 us pre_process: 475 us infer: 19163 us post_process: 369 us get show: 12630 us pre_process: 222 us infer: 19813 us post_process: 377 us get show: 13391 us
> 
> 可以看到 前处理 不到1ms，推理不到20ms，后处理不到1ms， get show 是13ms(平均) 采用多线程加速，实际帧率是看get show，也就是平均13ms一帧， fps 76帧

跑之前定频了嘛，运行的时候可以查看一下NPU的使用率cat /sys/kernel/debug/rknpu/load
如果您希望跑到理论最大值的话，需要去增大src/main.cc下的threadNum变量，扩容线程池。仓库内threadNum=3的情况下我测试大概是98fps这样
之前测试的时候，图形界面的接口GTK和QT也会对结果产生影响，印象中一个比另一个强10%左右，反映到Ubuntu上大抵是wayland和xorg下的差异。不过fork中并没有用到显示，对于实际表现应该没啥影响？

**Comment by YCG1** [comment]
> 修改的部分请看：https://github.com/1qingfeng-1/rknn-cpp-Multithreading.git
> 
> ./rknn_yolov5_demo model/RK3588/yolov5s-640-640.rknn 输出.mp4
> 
> 输出.mp4 是640*640 60帧的视频
> 
> 各个步骤耗时 测试结果： pre_process： 491 US 推断： 19065 US post_process： 403 US 获取显示： 13960 US pre_process： 183 US 推断： 19784 US post_process： 366 US 获取显示： 11874 US pre_process： 298 US 推断： 18670 US post_process： 415 US 获取显示： 11531 US pre_process： 475 US 推断： 19163 US post_process： 369 美国 GET 显示：12630 US pre_process：222 US 推断：19813 US post_process：377 US GET 显示：13391 US
> 
> 可以看到 前处理 不到1ms，推理不到20ms，后处理不到1ms， get show 是13ms（平均） 采用多线程加速，实际帧率是看get show，也就是平均13ms一帧， fps 76帧

首先定频

**Comment by 1qingfeng-1** [comment]
@leafqycc 
定频拉到最高频率，三个npu每个负载42%
修改threadNum=3，6，8，12，实际不会有太大帧率提高，12和3相差不大
单个npu处理时间在22ms, 理论上rk3588最高帧率可以达到 45*3 136帧的

**Comment by YCG1** [comment]
> @leafqycc 定频拉到最高频率，三个npu每个负载42% 修改threadNum=3，6，8，12，实际不会有太大帧率提高，12和3相差不大 单个npu处理时间在22ms, 理论上rk3588最高帧率可以达到 45*3 136帧的

我自己写了一套实现的 定频 v5s relu 单核npu可以拉到92%定死92  FPS 60左右 模型越大效果越好 v5m v7可以超过官方的测速

**Comment by YCG1** [comment]
> @leafqycc 定频拉到最高频率，三个npu每个负载42% 修改threadNum=3，6，8，12，实际不会有太大帧率提高，12和3相差不大 单个npu处理时间在22ms, 理论上rk3588最高帧率可以达到 45*3 136帧的

有兴趣可以加我QQ 1281854907  
![304AAECE8F4E13B3F167541C21F58458](https://github.com/leafqycc/rknn-cpp-Multithreading/assets/46243496/3dbad59d-dc54-4884-a643-948aae12a125)
![A5AE9323626166BF60C437703AB1E849](https://github.com/leafqycc/rknn-cpp-Multithreading/assets/46243496/90be376a-3b42-445d-a9b3-7827f6b99db7)

**Comment by 1qingfeng-1** [comment]
@YCG1 
npu就是跑不满，不知道是什么问题
![image](https://github.com/leafqycc/rknn-cpp-Multithreading/assets/33478786/8b800e8b-87d9-4b1c-a47d-42ba97bdd1cc)

**Comment by 1qingfeng-1** [comment]
@YCG1 你可以拉一下我修改的，测一下，多线程加跑不满npu

**Comment by leafqycc** [comment]
> @YCG1 npu就是跑不满，不知道是什么问题 ![image](https://private-user-images.githubusercontent.com/33478786/297948607-8b800e8b-87d9-4b1c-a47d-42ba97bdd1cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzQzMjcsIm5iZiI6MTcwNTY3NDAyNywicGF0aCI6Ii8zMzQ3ODc4Ni8yOTc5NDg2MDctOGI4MDBlOGItODdkOS00YjFjLWE0N2QtNDJiYTk3YmRkMWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE0MjAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NTFlM2QxMzhjMDM3ODlkNDM2MGRkNThjN2NkZTJiODNiYjJkOWY4MGNkYzVlZDhmNWNlODRkMGM3M2VhOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F4pwJUzIUgTpuzNmhJoE---5OitvCNCyuRp_hD9QT10)

会是视频解码效率低导致推理阻塞吗？直接使用opencv播放视频看看解码效率呢？（就不进行推理直接返回结果）
