### ISSUE TITLE
rk3588有没有出现过死机问题的?

### ISSUE THREAD

**Issue by Pi-Boss** [leafqycc/rknn-cpp-Multithreading#48]
我用这个仓库改了份yolov8的。在非root下运行程序，前几秒运行还是正常的，npu利用率挺高，然后系统就直接死机重启了。毫无征兆的那种~~~  @leafqycc

**Comment by Pi-Boss** [comment]
更新npu驱动后问题解决

**Comment by kywish** [comment]
请问是更新驱动到了什么版本，以及卡死的时候是什么版本？
我现在也有这个问题
