### ISSUE TITLE
读取mp4仅有4FPS

### ISSUE THREAD

**Issue by Leo5050xvjf** [leafqycc/rknn-cpp-Multithreading#51]
请问这可能是什么原因造成的？我的librknnrt.so 和 librga.so 和librknn_api.so都是取自rknn model zoo 2.1.0

1. Model: YOLOv5s
2. input size 640 640
3. activation function: relu
4. threadNum=1, FPS=4, threadNum=2, FPS=8
6. target platform: RK3576 
7. OS: ```Linux sige5 6.1.57 #30 SMP Wed Jun 19 11:37:28 CST 2024 aarch64 GNU/Linux```

screen shot:![image](https://github.com/user-attachments/assets/8a1e7f65-7806-46e1-9983-d334840f448a)

**Comment by leafqycc** [comment]
> 请问这可能是什么原因造成的？我的librknnrt.so 和 librga.so 和librknn_api.so都是取自rknn model zoo 2.1.0
> 
> 1. Model: YOLOv5s
> 2. input size 640 640
> 3. activation function: relu
> 4. threadNum=1, FPS=4, threadNum=2, FPS=8
> 5. target platform: RK3576
> 6. OS: `Linux sige5 6.1.57 #30 SMP Wed Jun 19 11:37:28 CST 2024 aarch64 GNU/Linux`
> 
> screen shot:![image](https://private-user-images.githubusercontent.com/61929063/359733604-8a1e7f65-7806-46e1-9983-d334840f448a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3Mzc0ODgsIm5iZiI6MTcyNTczNzE4OCwicGF0aCI6Ii82MTkyOTA2My8zNTk3MzM2MDQtOGExZTdmNjUtNzgwNi00NmUxLTk5ODMtZDMzNDg0MGY0NDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDE5MjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MGRjMDFmMGNmNTZkYTcxNzJlNzY4NWQ2OTdmOWNhMGU0YTg1NGNkOTBmZTkyNGIyNTdhMzY1YmU5OTllOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cRoav4cvd-cMgZwhPKuVvlPaARnNsd9yPT2QpigbTuE)

仓库main分支只适配了v1.5.2，我猜是版本兼容性问题？不过您这个能跑也是很神奇了（），之前有人用v2.0.0的库都跑不起来

**Comment by Leo5050xvjf** [comment]
解决了，结果是我后处理有地方写错!
